version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.17
    container_name: mosquitto
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python_backend
    volumes:
        - ./backend/logs:/app/logs
    depends_on:
      - mosquitto
    restart: unless-stopped